name: pdf_generator
description: "Generate PDF files from Flutter applications"
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  bloc: ^9.0.0
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.3.3
  file_picker: ^10.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^15.0.0
  json_annotation: ^4.9.0
  permission_handler: ^12.0.0+1
  qr_flutter: ^4.1.0
  syncfusion_flutter_core: ^29.1.38
  syncfusion_flutter_pdf: ^29.1.38
  syncfusion_flutter_pdfviewer: ^29.1.38

dev_dependencies:
  build_runner: ^2.4.10
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Arial
      fonts:
        - asset: assets/fonts/arial.ttf
